version: "2"

services:
    wsserver:
      image: "coffeelovers/wsserver"
      ports:
          - "8085:8085"
      networks:
          - "main"

networks:
    main:
        external:
            name: "main"